from sqlalchemy.orm import Session
from app.database import SessionLocal
from app.models.value_mappings import ValueMappings

SEED_MAPPINGS = {
    "country": {
        "AF": "Afghanistan",
        "AX": "\u00c5land Islands",
        "AL": "Albania",
        "DZ": "Algeria",
        "AS": "American Samoa",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguilla",
        "AQ": "Antarctica",
        "AG": "Antigua & Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BE": "Belgium",
        "BZ": "Belize",
        "BJ": "Benin",
        "BM": "Bermuda",
        "BT": "Bhutan",
        "BO": "Bolivia",
        "BA": "Bosnia & Herzegovina",
        "BW": "Botswana",
        "BV": "Bouvet Island",
        "BR": "Brazil",
        "IO": "British Indian Ocean Territory",
        "VG": "British Virgin Islands",
        "BN": "Brunei",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "CV": "Cape Verde",
        "BQ": "Caribbean Netherlands",
        "KY": "Cayman Islands",
        "CF": "Central African Republic",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CX": "Christmas Island",
        "CC": "Cocos (Keeling) Islands",
        "CO": "Colombia",
        "KM": "Comoros",
        "CG": "Congo - Brazzaville",
        "CD": "Congo - Kinshasa",
        "CK": "Cook Islands",
        "CR": "Costa Rica",
        "CI": "C\u00f4te d\u2019Ivoire",
        "HR": "Croatia",
        "CU": "Cuba",
        "CW": "Cura\u00e7ao",
        "CY": "Cyprus",
        "CZ": "Czechia",
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "EE": "Estonia",
        "SZ": "Eswatini",
        "ET": "Ethiopia",
        "FK": "Falkland Islands",
        "FO": "Faroe Islands",
        "FJ": "Fiji",
        "FI": "Finland",
        "FR": "France",
        "GF": "French Guiana",
        "PF": "French Polynesia",
        "TF": "French Southern Territories",
        "GA": "Gabon",
        "GM": "Gambia",
        "GE": "Georgia",
        "DE": "Germany",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Greece",
        "GL": "Greenland",
        "GD": "Grenada",
        "GP": "Guadeloupe",
        "GU": "Guam",
        "GT": "Guatemala",
        "GG": "Guernsey",
        "GN": "Guinea",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haiti",
        "HM": "Heard & McDonald Islands",
        "HN": "Honduras",
        "HK": "Hong Kong SAR China",
        "HU": "Hungary",
        "IS": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran",
        "IQ": "Iraq",
        "IE": "Ireland",
        "IM": "Isle of Man",
        "IL": "Israel",
        "IT": "Italy",
        "JM": "Jamaica",
        "JP": "Japan",
        "JE": "Jersey",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KI": "Kiribati",
        "XK": "Kosovo",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Laos",
        "LV": "Latvia",
        "LB": "Lebanon",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "LI": "Liechtenstein",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MO": "Macao SAR China",
        "MG": "Madagascar",
        "MW": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "MH": "Marshall Islands",
        "MQ": "Martinique",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "YT": "Mayotte",
        "MX": "Mexico",
        "FM": "Micronesia",
        "MD": "Moldova",
        "MC": "Monaco",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MS": "Montserrat",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "MM": "Myanmar (Burma)",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NC": "New Caledonia",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NF": "Norfolk Island",
        "KP": "North Korea",
        "MK": "North Macedonia",
        "MP": "Northern Mariana Islands",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PW": "Palau",
        "PS": "Palestinian Territories",
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippines",
        "PN": "Pitcairn Islands",
        "PL": "Poland",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "RE": "R\u00e9union",
        "RO": "Romania",
        "RU": "Russia",
        "RW": "Rwanda",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "S\u00e3o Tom\u00e9 & Pr\u00edncipe",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SX": "Sint Maarten",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "SO": "Somalia",
        "ZA": "South Africa",
        "GS": "South Georgia & South Sandwich Islands",
        "KR": "South Korea",
        "SS": "South Sudan",
        "ES": "Spain",
        "LK": "Sri Lanka",
        "BL": "St. Barth\u00e9lemy",
        "SH": "St. Helena",
        "KN": "St. Kitts & Nevis",
        "LC": "St. Lucia",
        "MF": "St. Martin",
        "PM": "St. Pierre & Miquelon",
        "VC": "St. Vincent & Grenadines",
        "SD": "Sudan",
        "SR": "Suriname",
        "SJ": "Svalbard & Jan Mayen",
        "SE": "Sweden",
        "CH": "Switzerland",
        "SY": "Syria",
        "TW": "Taiwan",
        "TJ": "Tajikistan",
        "TZ": "Tanzania",
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad & Tobago",
        "TN": "Tunisia",
        "TR": "Turkey",
        "TM": "Turkmenistan",
        "TC": "Turks & Caicos Islands",
        "TV": "Tuvalu",
        "UM": "U.S. Outlying Islands",
        "VI": "U.S. Virgin Islands",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": "United Kingdom",
        "US": "United States",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VU": "Vanuatu",
        "VA": "Vatican City",
        "VE": "Venezuela",
        "VN": "Vietnam",
        "WF": "Wallis & Futuna",
        "EH": "Western Sahara",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe"
    },
    "currency": {
        "EUR": "Euro",
        "USD": "US Dollar",
        "GBP": "British Pound",
        "CHF": "Swiss Franc",
        "JPY": "Japanese Yen",
        "CNY": "Chinese Yuan",
        "AUD": "Australian Dollar",
        "CAD": "Canadian Dollar",
        "SEK": "Swedish Krona",
        "NOK": "Norwegian Krone",
        "DKK": "Danish Krone",
        "PLN": "Polish Zloty",
        "CZK": "Czech Koruna",
        "HUF": "Hungarian Forint",
        "TRY": "Turkish Lira",
        "INR": "Indian Rupee",
        "BRL": "Brazilian Real",
        "ZAR": "South African Rand",
        "MXN": "Mexican Peso",
        "SGD": "Singapore Dollar",
        "NZD": "New Zealand Dollar",
        "HKD": "Hong Kong Dollar",
        "KRW": "South Korean Won",
        "RUB": "Russian Ruble",
        "ILS": "Israeli Shekel",
        "AED": "UAE Dirham",
        "SAR": "Saudi Riyal",
        "THB": "Thai Baht",
        "MYR": "Malaysian Ringgit",
        "IDR": "Indonesian Rupiah"
    },
    "device": {
        "desktop": "Desktop",
        "mobile": "Mobile",
        "tablet": "Tablet",
        "laptop": "Laptop",
    },
    "channel": {
        "direct": "Direct",
        "referral": "Referral",
        "affiliate": "Affiliate",
        "email": "Email",
        "sms": "SMS",
        "organicSearch": "Organic Search",
        "organicSocial": "Organic Social",
        "organicShopping": "Organic Shopping",
        "organicVideo": "Organic Video",
        "paidAds": "Paid Ads",
        "paidSearch": "Paid Search",
        "paidSocial": "Paid Social",
        "paidShopping": "Paid Shopping",
        "paidVideo": "Paid Video",
    },
    "browser": {
        "android": "Android",
        "aol": "AOL",
        "beaker": "Beaker",
        "bb10": "BlackBerry 10",
        "chrome": "Chrome",
        "chromium-webview": "Chrome (webview)",
        "crios": "Chrome (iOS)",
        "curl": "Curl",
        "edge": "Edge",
        "edge-chromium": "Edge (Chromium)",
        "edge-ios": "Edge (iOS)",
        "facebook": "Facebook",
        "firefox": "Firefox",
        "fxios": "Firefox (iOS)",
        "ie": "IE",
        "instagram": "Instagram",
        "ios": "iOS",
        "ios-webview": "iOS (webview)",
        "kakaotalk": "KakaoTalk",
        "miui": "MIUI",
        "opera": "Opera",
        "opera-mini": "Opera Mini",
        "phantomjs": "PhantomJS",
        "safari": "Safari",
        "samsung": "Samsung",
        "silk": "Silk",
        "searchbot": "Searchbot",
        "yandexbrowser": "Yandex",
    }
}

def seed():
    db: Session = SessionLocal()

    print("🌱 Seeding value mappings...")

    for mapping_type, items in SEED_MAPPINGS.items():
        for key, value in items.items():
            exists = db.query(ValueMappings).filter_by(type=mapping_type, key=key).first()
            if not exists:
                # print(f"➕ Adding mapping: {mapping_type} -> {key} = {value}")
                db.add(ValueMappings(type=mapping_type, key=key, value=value))

    db.commit()
    db.close()
    print("✅ Done seeding value mappings.")
