name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          use-docker-cli: true

      # Frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-frontend:latest
            ghcr.io/${{ github.repository }}-frontend:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # Backend
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-backend:latest
            ghcr.io/${{ github.repository }}-backend:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # Worker
      - name: Build and push worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-worker:latest
            ghcr.io/${{ github.repository }}-worker:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # Beat
      - name: Build and push beat
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker/beat.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-beat:latest
            ghcr.io/${{ github.repository }}-beat:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
