name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          use-docker-cli: true

      # -------- FRONTEND --------
      - name: Meta (frontend)
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-frontend
          tags: |
            type=raw,value=latest
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=UmamiSender Frontend
            org.opencontainers.image.description=Next.js frontend for UmamiSender.
            org.opencontainers.image.authors=${{ github.actor }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

      # -------- BACKEND --------
      - name: Meta (backend)
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-backend
          tags: |
            type=raw,value=latest
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=UmamiSender Backend
            org.opencontainers.image.description=FastAPI backend and REST API for UmamiSender.
            org.opencontainers.image.authors=${{ github.actor }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      # -------- WORKER --------
      - name: Meta (worker)
        id: meta-worker
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-worker
          tags: |
            type=raw,value=latest
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=UmamiSender Worker
            org.opencontainers.image.description=Celery worker processing async jobs.
            org.opencontainers.image.authors=${{ github.actor }}

      - name: Build and push worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker/Dockerfile
          push: true
          tags: ${{ steps.meta-worker.outputs.tags }}
          labels: ${{ steps.meta-worker.outputs.labels }}

      # -------- BEAT --------
      - name: Meta (beat)
        id: meta-beat
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-beat
          tags: |
            type=raw,value=latest
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=UmamiSender Beat
            org.opencontainers.image.description=Celery beat scheduler for periodic tasks.
            org.opencontainers.image.authors=${{ github.actor }}

      - name: Build and push beat
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker/beat.Dockerfile
          push: true
          tags: ${{ steps.meta-beat.outputs.tags }}
          labels: ${{ steps.meta-beat.outputs.labels }}